contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bamtoichorcna channel"
    url: https://nfcore.slack.com/channels/bamtoichorcna
    about: Discussion about the nf-core/bamtoichorcna pipeline
